[[NUMA]]
arch = "aarch64"
git-tree-sha1 = "847f098a30d086ac2c5cfa093fc75aad9d01dcc9"
libc = "glibc"
os = "linux"

    [[NUMA.download]]
    sha256 = "616c5bf19405fff3dbf93d3c4c5e4a985cc8344cf80599819a136ced243639f2"
    url = "https://github.com/JuliaBinaryWrappers/NUMA_jll.jl/releases/download/NUMA-v2.0.14+0/NUMA.v2.0.14.aarch64-linux-gnu.tar.gz"
[[NUMA]]
arch = "aarch64"
git-tree-sha1 = "bedd1aa4cd8d87aafac0119871a4314c5805e165"
libc = "musl"
os = "linux"

    [[NUMA.download]]
    sha256 = "ca577dd1c90a1cd41419369ff2fed98dfcfc96f7b45a7f5a6e559b01776f7202"
    url = "https://github.com/JuliaBinaryWrappers/NUMA_jll.jl/releases/download/NUMA-v2.0.14+0/NUMA.v2.0.14.aarch64-linux-musl.tar.gz"
[[NUMA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f4b3363852f345d389bee511ced0beef61223022"
libc = "glibc"
os = "linux"

    [[NUMA.download]]
    sha256 = "eaaa60deaaf0ee6ae0cbcb8eb200ea4bbfbca52090215c53b621a29eb7d765b5"
    url = "https://github.com/JuliaBinaryWrappers/NUMA_jll.jl/releases/download/NUMA-v2.0.14+0/NUMA.v2.0.14.armv6l-linux-gnueabihf.tar.gz"
[[NUMA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2468a456048584dae92b953759fff489f4179ae4"
libc = "musl"
os = "linux"

    [[NUMA.download]]
    sha256 = "2347e91668181283765082392526ffbede8d12021155afccfc39fd9ed11c33c9"
    url = "https://github.com/JuliaBinaryWrappers/NUMA_jll.jl/releases/download/NUMA-v2.0.14+0/NUMA.v2.0.14.armv6l-linux-musleabihf.tar.gz"
[[NUMA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0e56ef04e574905964b799380a1f23573f2c02b9"
libc = "glibc"
os = "linux"

    [[NUMA.download]]
    sha256 = "60938c776890627ab3e136c48860a8791ceea2be9e3f2dd814d13d0060df3c8a"
    url = "https://github.com/JuliaBinaryWrappers/NUMA_jll.jl/releases/download/NUMA-v2.0.14+0/NUMA.v2.0.14.armv7l-linux-gnueabihf.tar.gz"
[[NUMA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "071725711c419374cec12f4c3714b6694b2b6c38"
libc = "musl"
os = "linux"

    [[NUMA.download]]
    sha256 = "3089175add0c89e4767da4b2e6c0e702f6d51465e8e9d28029065310161f3055"
    url = "https://github.com/JuliaBinaryWrappers/NUMA_jll.jl/releases/download/NUMA-v2.0.14+0/NUMA.v2.0.14.armv7l-linux-musleabihf.tar.gz"
[[NUMA]]
arch = "i686"
git-tree-sha1 = "1d7359eab8e7b497ee656e1988d1f0dca5f43a78"
libc = "glibc"
os = "linux"

    [[NUMA.download]]
    sha256 = "a1bfd18b1b7bfef7abd01024cf52c4d484260a9e599b47d67b6d70bf98878a74"
    url = "https://github.com/JuliaBinaryWrappers/NUMA_jll.jl/releases/download/NUMA-v2.0.14+0/NUMA.v2.0.14.i686-linux-gnu.tar.gz"
[[NUMA]]
arch = "i686"
git-tree-sha1 = "6133ef596debc0836b70c02c34a6b2893bc6ff6a"
libc = "musl"
os = "linux"

    [[NUMA.download]]
    sha256 = "9b50155adb7c1c97a89df636f49c9cc3ae8fee1e96df95a62e356b24a7e9145d"
    url = "https://github.com/JuliaBinaryWrappers/NUMA_jll.jl/releases/download/NUMA-v2.0.14+0/NUMA.v2.0.14.i686-linux-musl.tar.gz"
[[NUMA]]
arch = "powerpc64le"
git-tree-sha1 = "65e411d612398389a5587e1aa7a4b6c17f9c4cc5"
libc = "glibc"
os = "linux"

    [[NUMA.download]]
    sha256 = "9f4247c4e2f27071882d9500ae2708ba30b17f78d00216a859425826dd2161e1"
    url = "https://github.com/JuliaBinaryWrappers/NUMA_jll.jl/releases/download/NUMA-v2.0.14+0/NUMA.v2.0.14.powerpc64le-linux-gnu.tar.gz"
[[NUMA]]
arch = "x86_64"
git-tree-sha1 = "022584ab361718f1eb76273f5ebf228ff43c8eb5"
libc = "glibc"
os = "linux"

    [[NUMA.download]]
    sha256 = "4cc75258a036d5664ead34827459129042244c2e1baabb65a184e8d7a2a494b6"
    url = "https://github.com/JuliaBinaryWrappers/NUMA_jll.jl/releases/download/NUMA-v2.0.14+0/NUMA.v2.0.14.x86_64-linux-gnu.tar.gz"
[[NUMA]]
arch = "x86_64"
git-tree-sha1 = "8e6c304941a75df06c54ba291cb55317aacb5cf7"
libc = "musl"
os = "linux"

    [[NUMA.download]]
    sha256 = "aeaf5f482800954f85f26a0116b8fa5f5a0434fdef75fa30480c329f45610312"
    url = "https://github.com/JuliaBinaryWrappers/NUMA_jll.jl/releases/download/NUMA-v2.0.14+0/NUMA.v2.0.14.x86_64-linux-musl.tar.gz"
