[[NUMA]]
arch = "i686"
git-tree-sha1 = "309a0ed8bb80e468390be15ce554e664f4b4b105"
libc = "glibc"
os = "linux"

    [[NUMA.download]]
    sha256 = "5db6dfd365ea9e550f66277f0916442ca5b4340e7d8d0087df4c779f051c548a"
    url = "https://github.com/JuliaBinaryWrappers/NUMA_jll.jl/releases/download/NUMA-v2.0.13+0/NUMA.v2.0.13.i686-linux-gnu.tar.gz"
[[NUMA]]
arch = "armv7l"
git-tree-sha1 = "7f5cb8183135a14c0562eed5dfa249870c0345d7"
libc = "glibc"
os = "linux"

    [[NUMA.download]]
    sha256 = "a4154887b8fcbbb4dcf019c7c57aef3ba7952cd0b297219289ecce1ae30ce960"
    url = "https://github.com/JuliaBinaryWrappers/NUMA_jll.jl/releases/download/NUMA-v2.0.13+0/NUMA.v2.0.13.arm-linux-gnueabihf.tar.gz"
[[NUMA]]
arch = "armv7l"
git-tree-sha1 = "03704dedcb142ac9d0792b9bf03d8792aa206bf5"
libc = "musl"
os = "linux"

    [[NUMA.download]]
    sha256 = "618270108ba36c2d7ad1cb654b46dbbc35c6d4b934515434dbf9ac002944a9fe"
    url = "https://github.com/JuliaBinaryWrappers/NUMA_jll.jl/releases/download/NUMA-v2.0.13+0/NUMA.v2.0.13.arm-linux-musleabihf.tar.gz"
[[NUMA]]
arch = "i686"
git-tree-sha1 = "4e9209e4b9e8efeafc3e726964fa78e6cd3de34d"
libc = "musl"
os = "linux"

    [[NUMA.download]]
    sha256 = "c1ea179a8503913deefe60b0680405eb3e364d5816878b491e6fee3161890a4e"
    url = "https://github.com/JuliaBinaryWrappers/NUMA_jll.jl/releases/download/NUMA-v2.0.13+0/NUMA.v2.0.13.i686-linux-musl.tar.gz"
[[NUMA]]
arch = "x86_64"
git-tree-sha1 = "b99aa27d8174901d7f4c184b0ddbd171cdb8f419"
libc = "glibc"
os = "linux"

    [[NUMA.download]]
    sha256 = "f9ccceceec32f8edfb5468762d3d81840fb1f5bebb85d8ef9b20df86d7c02087"
    url = "https://github.com/JuliaBinaryWrappers/NUMA_jll.jl/releases/download/NUMA-v2.0.13+0/NUMA.v2.0.13.x86_64-linux-gnu.tar.gz"
[[NUMA]]
arch = "aarch64"
git-tree-sha1 = "4aec2f72fbeff96e90ee3e463279280c78faf361"
libc = "glibc"
os = "linux"

    [[NUMA.download]]
    sha256 = "235dfa7f51384ee3f2fe8ed1e5a166084ef1c1fa541207883946507d0071cb3c"
    url = "https://github.com/JuliaBinaryWrappers/NUMA_jll.jl/releases/download/NUMA-v2.0.13+0/NUMA.v2.0.13.aarch64-linux-gnu.tar.gz"
[[NUMA]]
arch = "powerpc64le"
git-tree-sha1 = "efd2d19f774d3f50ed53915c4981f32633378d36"
libc = "glibc"
os = "linux"

    [[NUMA.download]]
    sha256 = "68aeb30c7fcecc452dec90d967e7aa5e8e5c14d70bba6565f66e1f45e7957864"
    url = "https://github.com/JuliaBinaryWrappers/NUMA_jll.jl/releases/download/NUMA-v2.0.13+0/NUMA.v2.0.13.powerpc64le-linux-gnu.tar.gz"
[[NUMA]]
arch = "x86_64"
git-tree-sha1 = "a4f4b97ec8c74a06756ce46f04da43d84949d4a8"
libc = "musl"
os = "linux"

    [[NUMA.download]]
    sha256 = "66577bfcd956dba4ce1c468f8841fc51fa240b97fe45335279f2cc574638837e"
    url = "https://github.com/JuliaBinaryWrappers/NUMA_jll.jl/releases/download/NUMA-v2.0.13+0/NUMA.v2.0.13.x86_64-linux-musl.tar.gz"
[[NUMA]]
arch = "aarch64"
git-tree-sha1 = "0d9502648411112b58cc7ea3c56b66f9eaf5c21d"
libc = "musl"
os = "linux"

    [[NUMA.download]]
    sha256 = "180efb7e5e59d01dd01b61b6ec948512737797290c4a8a20d8ee0b06fcb83c90"
    url = "https://github.com/JuliaBinaryWrappers/NUMA_jll.jl/releases/download/NUMA-v2.0.13+0/NUMA.v2.0.13.aarch64-linux-musl.tar.gz"
